config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :courts do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:delete, :index]
  get '/pages/card', to: 'pages#card'
end

app/models/court.rb
class Court < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :users, through: :bookings
  validates :address, presence: true
  validates :price, presence: true
  has_many_attached :photos
  validates :category, inclusion: { in: %w(Indoor Outdoor) }
  validates :surfaces, inclusion: { in: %w(Clay Hardcore Grass Concrete) }
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/courts_controller.rb
class CourtsController < ApplicationController
  before_action :authenticate_user!, only: :new

  # rubocop:disable Metrics/MethodLength
  def index
    @courts = Court.all
    num = params[:price_range].to_f
    location = params[:location]
    surfaces = params[:surface_type]
    price_query = Court.where(price: 10..num)
    location_query = Court.where(address: location)
    surface_query = Court.where(surfaces: surfaces)

    @collect = price_query + location_query + surface_query
    @collect = @collect.uniq
    @collect = @courts if @collect.empty?
    @collect.map do |court|
      {
        lat: court.latitude,
        lng: court.longitude
      }
    end
    @markers = @collect.map do |court|
      {
        lat: court.latitude,
        lng: court.longitude,
        info_window: render_to_string(partial: "info_window", locals: { court: court }),
        image_url: helpers.asset_url('map-marker3.png')
      }
    end
  end
  # rubocop:enable Metrics/MethodLength

  def show
    @court = Court.find(params[:id])
    @booking = Booking.new
    @markers = [{
      lat: @court.latitude,
      lng: @court.longitude,
      info_window: render_to_string(partial: "info_window", locals: { court: @court }),
      image_url: helpers.asset_url('map-marker3.png')
    }]
  end

  def new
    @court = Court.new
  end

  def create
    @court = Court.new(court_params)
    @court.user = current_user

    if @court.save!
      redirect_to courts_path
    else
      render :new
    end
  end

  private

  def court_params
    params.require(:court).permit(:user_id, :address, :title, :price, :description, :surfaces, :category, photos: [])
  end
end

app/views/courts/_info_window.html.erb
<%= cl_image_tag court.photos[0].key, alt: "alttext" %>
<p><strong><%= court.title %></strong></p>

app/views/courts/index.html.erb
<%= render 'pages/navbar2' %>
<div id="courts-index-page">
  <div class="courts-index-container">
    <% @collect.each do |court| %>
      <a href="/courts/<%= court.id %>", class="btn text-decoration-none">
        <div class="court-card-index-page">
          <% if court.photos.attached? %>
            <div class="court-image-index-page">
              <%= cl_image_tag court.photos[0].key, alt: "alttext" %>
            </div>
          <% else %>
            <div class="court-image-index-page">
              <%= image_tag 'https://media.architecturaldigest.com/photos/596d2d14fde163455758e211/master/w_1000,h_667,c_limit/goldstein.jpg', alt: "alttext", crop: :fill %>
            </div>
          <% end %>
          <div class="court-info-index-page">
            <p><strong><%= court.title %></strong></p>
            <p><%= court.description %></p>
          </div>
          <div class="court-price-index-page">
            <p><strong>£<%= court.price %>/Hr</strong></p>
          </div>
        </div>
      </a>
    <% end %>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
















<!-- <div class="container">
    
                  < @courts.each do |court| %>
                  <= link_to court_path(court.id), class: "text-decoration-none" do%>

                  <div class="card-product mt-3 p-3 btn">
                        < if court.photos.attached? >
                              < court.photos.each do |photo| >
                              <= cl_image_tag photo.key, height: 100, width: 120, crop: :fill >
                              < end >
                        < end >
                              <div class="card-trip-infos ml-3">
                                    <div>
                                          <h2><= court.address ></h2>
                                          <p><= court.description ></p>
                                    </div>
                                    <h2 class="card-trip-pricing card-trip-user">£<= court.price >/Hr</h2>
                              </div>
                        </div>
                        < end >
                  < end >
         
</div>
 -->

app/views/courts/new.html.erb
<%= render 'pages/navbar2' %>

<div class="bg-light shadow-lg mt-5 container p-3">
  <div class="row d-flex justify-content-center mt-3">
    <div class="col-9">
    <div class="bg-light p-4 rounded mx-auto w-75">
      <h3 class="mb-5">Please enter the details of your court below.</h3>
      <%= simple_form_for Court.new do |f| %>
      <%= f.input :address, placeholder: "555 Hillsbury" %>
      <%= f.input :title, placeholder: "Awesome tennis court in Madrid" %>
      <%= f.input :description, placeholder: "Why your court is the best" %>
      <%= f.input :price, as: :numeric, placeholder: "A whole lot of m's" %>
      <%= f.input :category, as: :radio_buttons, collection: %w(Indoor Outdoor) %>
      <%= f.input :surfaces, as: :radio_buttons, collection: %w(Clay Hardcore Grass Concrete) %>
      <%= f.input :photos, as: :file, input_html: { multiple: true }%>
      <div>
        <div class="d-inline-flex">
            <div class="col-6">
            <%= f.submit  class: "btn btn-success rounded mt-5 shadow-sm" %>
            </div>
            <div class="col-6">
              <%= link_to "Back", courts_path, class: "btn btn-secondary rounded mt-5 ml-2 shadow-sm" %>
            </div>
        </div>
      </div>
    <% end %>
    

    </div>
  </div>
</div>

app/views/courts/show.html.erb
<%= render 'pages/navbar2' %>
<div id="courts-index-page">
  <div class="courts-index-container m-5">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <% if @court.photos.attached? %>
          <% @court.photos.each do |photo| %>
            <div class="carousel-item active">
              <%= cl_image_tag photo.key, alt: "alttext", class: 'd-block w-100' %>
            </div>
          <% end %>
        <% else %>
          <div class="carousel-item active">
            <%= image_tag 'https://media.architecturaldigest.com/photos/596d2d14fde163455758e211/master/w_1000,h_667,c_limit/goldstein.jpg', alt: "alttext", class: 'd-block w-100' %>
          </div>
        <% end %>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
    <div class="court-show-container">
      <div class="description">
        <h3><%= @court.title %></h3>
        <p><%= @court.description %> </p>
      </div>
      <div class="info">
        <p>Price: <strong>£<%= @court.price %>/Hr</strong></p>
        <p>Category: <%= @court.category %> </p>
        <p>Surface: <%= @court.surfaces %> </p>
        <p>Address: <%= @court.address %></p>
      </div>
    </div>
    <div class="court-booking">
      <h3>Book this court</h3>
      <%= simple_form_for [@court, @booking] do |f| %>
      <%= f.input :start_time, label: "From", as: :string, required: false, input_html: {class: "datepicker"} %>
      <%= f.input :end_time, label: "To", as: :string, required: false, input_html: {class: "datepicker"} %>
      <div>
        <div class="d-inline-flex">
          <%= f.submit  class: "btn btn-success rounded mt-3 shadow-sm" %>
          <%= link_to "Back", courts_path, class: "btn btn-secondary rounded mt-3 ml-2 shadow-sm" %>
        </div>
      </div>
      <% end %>
    </div>
  </div>
  <div id="map" data-markers="<%= @markers.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>

<!-- <div class="container">
  <div class="row justify-content-center">
    <div class="col-8">
      < if @court.photos.attached? >
        <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
            < @court.photos.each do |photo| >
              <div class="carousel-item active">
                <= cl_image_tag photo.key, alt: "alttext", class: 'd-block w-100' >
              </div>
            < end >
          </div>
          <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      < end >
      <div class="court-show-container">
        <div class="description">
          <h3>Description</h3>
          <p><= @court.description > </p>
        </div>
        <div class="info">
          <p>Price: <strong>£<= @court.price >/Hr</strong></p>
          <p>Category: <= @court.category > </p>
          <p>Surface: <= @court.surfaces > </p>
          <p>Address: <= @court.address ></p>
        </div>
      </div>
      <div class="map-container">
        <img src="https://www.freecountrymaps.com/map/free/great_britain/wimbledon-map-great_britain-423749783.png" alt="">
      </div>
      <div class="court-show-btns">
        <div class="court-buttons">
          <= link_to "Back", courts_path, class: "btn btn-secondary" >
          <= link_to "Book this court", new_court_booking_path(@court), class: "btn btn-success" >
        </div>
      </div>
      </div>
    </div>
  </div>
</div> -->











<!--   < @court.photos[0] do |photo| >
              <div class="carousel-item active">
                <= cl_image_tag photo.key, alt: "alttext", class: 'd-block w-100' >
              </div>
            < end %>
            < if @court.photos.length > 1 %>
              < @court.photos[1..].each do |photo| %>
                <div class="carousel-item">
                  <= cl_image_tag photo.key, alt: "alttext", class: 'd-block w-100' %>
                </div>
              < end %>
            < end %> -->