config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :courts do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:delete, :index]
  get '/pages/card', to: 'pages#card'
end

app/views/pages/_navbar2.html.erb
<div class="banner">
    <nav class="navbar2 pr-4 pl-4 sticky">
<%# Nav Logo Row %>
      <div class="nav-logo d-flex">
        <i class="fas fa-table-tennis nav-logo-icon2 mr-1"></i>
        <%# <i class="fab fa-spotify nav-logo-icon shadow-sm p-3 mr-3 font-weight-bold"></i> %>
        <a href= / >
          <h3 class="font-weight-bold nav-logo-2">Sportify</h3>
        </a>
      </div>

<%# End Row %>
      <div class="d-inline-flex rounded text-center">
          <li class="navbar-link-end text-center">
            <a href="/courts" class="text-off-black">
              About Us
            </a>
          </li>
            <li class="navbar-link-end text-center">
            <%= link_to "Become a host", new_court_path, class:"text-off-black" %>
          </li>
          <li class="navbar-link-last m-0 text-center dropdown" id="dropdown_login">
            <a href="http://google.com" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bars m-0 burger-icon text-off-black"></i>
              <div class="dropdown-menu rounded" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#">Edit Profile</a>
                <a class="dropdown-item border-top" href= /bookings>Bookings</a>
                  <% if user_signed_in? %>
                  <%= link_to "Log Out",  destroy_user_session_path, method: :delete, class: "dropdown-item border-top border-bottom" %>
                  <% else %> 
                  <%= link_to "Login", user_session_path, class: "dropdown-item border-top border-bottom" %>
                  <% end %>
              </div>
            </a>
            <a href="#">
              <%# <i class="fas fa-user m-0" id="login-icon"></i> %>
              <div id="login-icon" class="material-icons mdl-badge mdl-badge--overlap" data-badge="1">account_box</div>
            </a>
          </li>
      
      </div>

    </nav>
</div>

app/views/pages/_navbarMain.html.erb
<div class="banner">
    <nav class="navbar sticky p-4" id = "navy">
<%# Nav Logo Row %>
      <div class="nav-logo d-flex">
        <i class="fas fa-table-tennis nav-logo-icon mr-1"></i>
        <%# <i class="fab fa-spotify nav-logo-icon shadow-sm p-3 mr-3 font-weight-bold"></i> %>
        <a href= / >
          <h3 class="font-weight-bold text-off-black">Sportify</h3>
        </a>
      </div>

<%# End Row %>
      <div class="d-inline-flex rounded text-center">
          <li class="navbar-link-end text-center">
            <a href="/courts">
              About Us
            </a>
          </li>
          <li class="navbar-link-end text-center">
            <%= link_to "Become a host", new_court_path %>
          </li>
          <li class="navbar-link-last m-0 text-center dropdown" id="dropdown_login">
            <a href="http://google.com" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-bars m-0 burger-icon"></i>
              <div class="dropdown-menu rounded" aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#">Edit Profile</a>
                <a class="dropdown-item border-top" href= /bookings>Bookings</a>
                  <% if user_signed_in? %>
                  <%= link_to "Log Out",  destroy_user_session_path, method: :delete, class: "dropdown-item border-top border-bottom" %>
                  <% else %> 
                  <%= link_to "Login", user_session_path, class: "dropdown-item border-top border-bottom" %>
                  <% end %>
              </div>
            </a>
            <a href="#">
              <%# <i class="fas fa-user m-0" id="login-icon"></i> %>
              <div id="login-icon" class="material-icons mdl-badge mdl-badge--overlap" data-badge="1">account_box</div>
            </a>
          </li>
      
      </div>

    </nav>
</div>

app/views/pages/_searchnav.html.erb
    <form class="search-navbar-container" method="get" action="/courts/">

    <%# Col 1 %>
      <div class="search-nav-col-1">
        <label class="search-nav-title">Location</label>
        <input class="search-nav-desc" type="text" name="location" placeholder="Where are you going">
      </div>
    <%# Col 2 %>
      <div class="search-nav-col">
        <label class="search-nav-title">Surface Type</label>
        <input class="search-nav-desc" type="text" name="surface_type" placeholder="Add dates">
      </div>
    <%# Col 3 %>
      <div class="search-nav-col">
        <label class="search-nav-title">Check out</label>
        <input class="search-nav-desc" type="text" name="check_out" placeholder="Add dates">
      </div>
    <%# Col 4 %>
      <div class="d-inline-flex align-items-center">
        <div class="search-nav-col col-9">
          <select name="price_range" class="custom-select search-nav-desc" id="price_range">
            <option>Price Range...</option>
            <option value=20.0>Budget</option>
            <option value=40.0>Premium</option>
            <option value=60.0>Luxury</option>
          </select>
        </div>
        <div class="col-3">
          <button type="submit" class="fas fa-search pink-icon-lg"></button>
        </div>
      </div>
    </form>
    

app/views/pages/card.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#staticBackdrop">
  Launch static backdrop modal
</button>

<!-- Modal -->
<div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
      <div class="container">
                <h2>Log in</h2>

            <%= simple_form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
              <div class="form-inputs">
                <%= f.input :email,
                            required: false,
                            autofocus: true,
                            input_html: { autocomplete: "email" } %>
                <%= f.input :password,
                            required: false,
                            input_html: { autocomplete: "current-password" } %>
                <%= f.input :remember_me, as: :boolean if devise_mapping.rememberable? %>
              </div>

              <div class="form-actions">
                <%= f.button :submit, "Log in" %>
              </div>
            <% end %>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Understood</button>
      </div>
    </div>
  </div>
</div>



































<br>
<br>
<!-- <h2>Play anywhere</h2> -->

<br>

<div class="card-container-3 mt-3">
  <div class="d-flex flex-column">
    <div class="court-card" >
      <img src="https://video-images.vice.com/_uncategorized/1537288581962-Coolest-Tennis-Courts-2.jpeg?resize=1575:*"/>
    </div>
    <div class="title1" title="Indoor courts">
        <p>Indoor courts</p>
    </div>
  </div>

  <div class="d-flex flex-column">
    <div class="court-card">
      <img src="https://video-images.vice.com/_uncategorized/1537289035114-Coolest-Tennis-Courts-6.jpeg?resize=1024:*"/>
        <div class="title1" title="Outdoor courts">
          <p>Outdoor courts</p>
        </div>
    </div>
  </div>

  <div class="d-flex flex-column">
    <div class="court-card">
      <img src="https://video-images.vice.com/_uncategorized/1537288324658-Coolest-Tennis-Courts-1.jpeg?resize=1575:*"/>
        <div class="title1" title="Unique locations">
          <p>Unique locations</p>
        </div>
    </div>
  </div>

</div>

<br>
<br>

<div class="large-court-card">
  <div class="heading">
    <h4>Become a host</h4>
    <p>Unlock new oppurtunities by sharing your space</p>
  </div>
</div>

<br>
<br>

<h2>Many possibilities</h2>

<br>

<div class="card-container-4 mt-3">

  <div class="d-flex flex-column">
    <div class="small-court-card" >
      <img src="https://video-images.vice.com/_uncategorized/1537288581962-Coolest-Tennis-Courts-2.jpeg?resize=1575:*"/>
    </div>
    <div class="title2" title="Grass">
        <p>Grass</p>
    </div>
  </div>

  <div class="d-flex flex-column">
    <div class="small-court-card">
      <img src="https://video-images.vice.com/_uncategorized/1537289035114-Coolest-Tennis-Courts-6.jpeg?resize=1024:*"/>
        <div class="title2" title="Clay">
          <p>Clay</p>
        </div>
    </div>
  </div>

  <div class="d-flex flex-column">
    <div class="small-court-card">
      <img src="https://video-images.vice.com/_uncategorized/1537288324658-Coolest-Tennis-Courts-1.jpeg?resize=1575:*"/>
        <div class="title2" title="Hard">
          <p>Hard</p>
        </div>
    </div>
  </div>

  <div class="d-flex flex-column">
    <div class="small-court-card">
      <img src="https://video-images.vice.com/_uncategorized/1537288324658-Coolest-Tennis-Courts-1.jpeg?resize=1575:*"/>
        <div class="title2" title="Artificial">
          <p>Artificial</p>
        </div>
    </div>
  </div>

</div>

<br>
<br>

<div class="footer">
  <div class="icons">
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-instagram-square"></i>
    <i class="fab fa-twitter-square"></i>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'pages/navbarMain' %>

<div class="diagonal-box">
  <div class="content">
    <div class="container w-100 justify-content-center d-flex col-xs-12 col-8">
        <%= render 'searchnav' %>
    </div>
    <div class="d-inline-flex mr-5">
      <div class="banner-image-container mr-5">
        <div class="row">
          <%= image_tag("kasatkina.png", class: 'banner-image col-6', alt: "Tennis pic") %>
        </div>
      </div>
    </div>
    <%# Banner Text %>
    <div class="container d-flex justify-content-end">
      <%# <%= link_to "COURTS", courts_path %>
      <div class="row justify-content-end">
          <div class="col-10 mt-5">
            <div class="display-2 mt-3 mb-1" id="banner-heading">
              Game. Set. Match.
            </div>
            <br>
            <%= link_to 'Find courts', courts_path, class: "banner-btn text-decoration-none" %>
          </div>
      </div>
    </div>
    <%# Grid 1 For Cards %>
    <div class="container-fluid border d-none">
      <div class="row">
        <div class="col-12">
        </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

<div class="home-page-container">
  <h2>Play anywhere</h2>

  <br>

  <div class="card-container-3 mt-3">
    <div class="d-flex flex-column">
      <div class="court-card" >
        <img src="https://video-images.vice.com/_uncategorized/1537288581962-Coolest-Tennis-Courts-2.jpeg?resize=1575:*"/>
      </div>
      <div class="title1" title="Indoor courts">
          <h5>Indoor courts</h5>
      </div>
    </div>

    <div class="d-flex flex-column">
      <div class="court-card">
        <img src="https://video-images.vice.com/_uncategorized/1537289035114-Coolest-Tennis-Courts-6.jpeg?resize=1024:*"/>
          <div class="title1" title="Outdoor courts">
            <h5>Outdoor courts</h5>
          </div>
      </div>
    </div>

    <div class="d-flex flex-column">
      <div class="court-card">
        <img src="https://video-images.vice.com/_uncategorized/1537288324658-Coolest-Tennis-Courts-1.jpeg?resize=1575:*"/>
          <div class="title1" title="Unique locations">
            <h5>Unique locations</h5>
          </div>
      </div>
    </div>

  </div>

  <br>
  <br>

  <a href="/courts/new" class="text-decoration-none">
    <div class="large-court-card">

      <div class="heading">
        <h4>Become a host</h4>
        <p>Unlock new oppurtunities by sharing your space</p>
      </div>

    </div>
  </a>


  <br>
  <br>

  <h2>Many possibilities</h2>

  <br>

  <div class="card-container-4 mt-3">

    <div class="d-flex flex-column">
      <div class="small-court-card" >
        <img src="https://www.liveabout.com/thmb/9KrxnEpqlbHlYMWZe6bEGIfd4W0=/3386x2257/filters:no_upscale():max_bytes(150000):strip_icc()/day-one--the-championships---wimbledon-2015-478964582-5928b0c45f9b585950957a32.jpg"/>
      </div>
      <div class="title2" title="Grass">
          <h5>Grass</h5>
      </div>
    </div>

    <div class="d-flex flex-column">
      <div class="small-court-card">
        <img src="https://images.ctfassets.net/3s5io6mnxfqz/5kW4pSkQOdRuuxUcmvewDt/3a9d1be5d4f3a8dabd1a66f94a126372/AdobeStock_309689038.jpeg"/>
          <div class="title2" title="Clay">
            <h5>Clay</h5>
          </div>
      </div>
    </div>

    <div class="d-flex flex-column">
      <div class="small-court-card">
        <img src="https://westchestermagazine.com/wp-content/uploads/sites/4/2019/06/hardcourt_AdobeStock_161291397.jpg"/>
          <div class="title2" title="Hard">
            <h5>Hard</h5>
          </div>
      </div>
    </div>

    <div class="d-flex flex-column">
      <div class="small-court-card">
        <img src="https://mk0turfgrassgdsd8tai.kinstacdn.com/wp-content/uploads/2020/03/artificial-grass-for-paddle-courts-4.jpg"/>
          <div class="title2" title="Artificial">
            <h5>Artificial</h5>
          </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>

<div class="footer">
  <div class="inc">© 2021 Sportify, Inc · Privacy · Terms · Sitemap · UK Modern Slavery Act · Company details</div>
  <br>
  <button type="button" class="btn btn-outline-primary">Choose a language</button> </div>
   <div class="icons">
    <i class="fab fa-facebook-square"></i>
    <i class="fab fa-instagram-square"></i>
    <i class="fab fa-twitter-square"></i>
  </div>
</div>